name: Release

on:
  push:
    tags: ['v*']

permissions:
  contents: write
  packages: write

jobs:
  build-artifex:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TAG=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: artifex
          push: true
          tags: |
            ghcr.io/curatorium/maximus-artifex:latest
            ghcr.io/curatorium/maximus-artifex:${{ env.TAG }}

  build-scribe:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TAG=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: scribe
          push: true
          tags: |
            ghcr.io/curatorium/maximus-scribe:latest
            ghcr.io/curatorium/maximus-scribe:${{ env.TAG }}

  release:
    needs: [build-artifex, build-scribe]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: softprops/action-gh-release@v2
        with:
          files: maximus
